version: 0.0
os: linux
files:
  - source: docker-compose.yml
    destination: /home/vmfrontdevops/FrontEnd
hooks:
  BeforeInstall:
    - location: scripts/vm-frontend-stop.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/vm-frontend-start.sh
      timeout: 120
      runas: vmfrontdevops
