const AdminNavaigationObject = {
    "roles": ["Admin"],
    "menu": {
        "navItems": [
            {
                name: "Home",
                icon: "",
                path: "/",
                hide: true,
                permission: "default",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Edit Profile",
                path: "/editProfile",
                hide: true,
                permission: "default",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Notification",
                path: "/dashboardNotification",
                hide: true,
                icon: "",
                permission: "add_notifications",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Email Notifications",
                path: "/emailNotification",
                hide: true,
                permission: "add_notifications",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Whatsapp Notifications",
                path: "/whatsappNotification",
                hide: true,
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "One Signal Notification",
                path: "/pushNotification",
                hide: true,
                permission: "add_notifications",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Company List",
                path: "/companies",
                hide: false,
                icon: "",
                permission: "list_companies",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Company Details",
                path: "/company",
                hide: true,
                permission: "list_companies",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Candidates List",
                path: "/candidates",
                hide: false,
                icon: "",
                permission: "list_candidates",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Candidate Details",
                path: "/candidate",
                hide: true,
                permission: "list_candidates",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Job Details",
                path: "/jobvalidate",
                hide: true,
                permission: "default",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "All Jobs",
                path: "/alljobs",
                hide: false,
                icon: "",
                permission: "default",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Interviews",
                path: "/interviews",
                hide: false,
                icon: "",
                permission: "default",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Xi Users List",
                path: "/xiuserslist",
                hide: false,
                icon: "",
                permission: "default",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Xi Panel",
                path: "/XIPanel",
                hide: false,
                icon: "",
                permission: "default",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Company Validation",
                path: "/companyValidate",
                hide: true,
                permission: "default",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Company Validation",
                path: "/cityValidate",
                hide: true,
                permission: "default",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Company Validation",
                path: "/titleValidate",
                hide: true,
                permission: "default",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Add Skills",
                path: "/addSkills",
                hide: false,
                icon: "",
                permission: "add_skills",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Add Admin User",
                path: "/addAdminUser",
                hide: false,
                icon: "",
                permission: "add_users",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "XIOnboarding",
                path: "/XIOnboarding",
                hide: false,
                icon: "",
                permission: "list_XI",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "Add Interview Questions",
                path: "/addinterviewQuestions",
                hide: false,
                icon: "",
                permission: "default",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "CPrintAble",
                path: "/CPrintAble",
                hide: true,
                icon: "",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "InterviewReport",
                path: "/user/InterviewReport/:id",
                hide: true,
                icon: "",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
            {
                name: "CPrintAble",
                path: "/CPrintAbleAdmin",
                hide: true,
                icon: "",
                roles: ["Admin"],
                enabled: true,
                locked: false,
            },
        ]
    }
}

export default AdminNavaigationObject;